"""The public gallery: a self-contained static site listing every preview.

This is the "public storage" half of the project, and it is deliberately built
to the same standard as the images themselves.

The assembled site talks to nothing but its own origin. No CDN, no web font,
no analytics, no script of any kind; the stylesheet is a same-origin file
rather than an inline block, so the page's own Content-Security-Policy can
refuse ``unsafe-inline`` instead of tolerating it. The result satisfies the
egress, CSP and privacy families of AGSSH-STD-001 as a static surface, and can
be checked with ``agssh`` once deployed.

Images are copied into the site at assembly time rather than committed twice,
so the repository keeps exactly one copy of every PNG.
"""

from __future__ import annotations

import html
import json
import os
import shutil
from typing import Dict, List, Tuple

from . import __version__
from .config import Manifest
from .errors import RenderError
from .model import Preview

#: Locks the page to its own origin. Expressed as a meta element because
#: GitHub Pages does not let a repository set response headers; a real
#: deployment behind a proxy should send the same policy as a header, which is
#: the stronger assurance tier.
CSP = (
    "default-src 'none'; "
    "img-src 'self'; "
    "style-src 'self'; "
    "base-uri 'none'; "
    "form-action 'none'; "
    "frame-ancestors 'none'"
)

STYLESHEET = """/* Generated by gspg. Same-origin, no imports, no web fonts. */
:root {
  color-scheme: light dark;
  --bg: #f6f7f9;
  --card: #ffffff;
  --ink: #14161a;
  --muted: #5b6270;
  --line: #e2e5ea;
  --accent: #2f6fed;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #0c0e12;
    --card: #14171d;
    --ink: #eceef2;
    --muted: #98a0ae;
    --line: #232833;
    --accent: #7aa2ff;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--bg);
  color: var(--ink);
  font: 15px/1.55 ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
}
main { max-width: 1180px; margin: 0 auto; padding: 56px 24px 96px; }
h1 { font-size: 30px; letter-spacing: -0.02em; margin: 0 0 10px; }
p.lede { color: var(--muted); margin: 0 0 10px; max-width: 68ch; }
p.meta { color: var(--muted); font-size: 13px; margin: 0 0 40px; }
.grid {
  display: grid;
  gap: 28px;
  grid-template-columns: repeat(auto-fill, minmax(340px, 1fr));
}
figure {
  margin: 0;
  background: var(--card);
  border: 1px solid var(--line);
  border-radius: 14px;
  overflow: hidden;
}
figure img {
  display: block;
  width: 100%;
  height: auto;
  aspect-ratio: 2 / 1;
  background: var(--line);
}
figcaption { padding: 14px 16px 16px; }
figcaption a { color: var(--ink); text-decoration: none; font-weight: 600; }
figcaption a:hover { color: var(--accent); }
figcaption .sub { color: var(--muted); font-size: 13px; margin-top: 4px; }
figcaption .tags { margin-top: 10px; display: flex; flex-wrap: wrap; gap: 6px; }
figcaption .tags span {
  font: 11px/1.6 ui-monospace, SFMono-Regular, Menlo, monospace;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--muted);
  border: 1px solid var(--line);
  border-radius: 999px;
  padding: 1px 8px;
}
footer {
  margin-top: 64px;
  padding-top: 24px;
  border-top: 1px solid var(--line);
  color: var(--muted);
  font-size: 13px;
}
footer p { max-width: 74ch; }
code {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 0.92em;
  overflow-wrap: anywhere;
}
"""


def _card(preview: Preview, image: str, entry: Dict[str, object]) -> str:
    # Repository facts live here rather than on the image: at feed size they
    # would be unreadable, but on a web page they are useful.
    tags = list(preview.facts)
    return """      <figure>
        <img src="%s" alt="Social preview for %s" width="1280" height="640" loading="lazy">
        <figcaption>
          <a href="https://github.com/%s">%s</a>
          <div class="sub">%s</div>
          <div class="tags">%s</div>
        </figcaption>
      </figure>""" % (
        html.escape(image),
        html.escape(preview.repo),
        html.escape(preview.repo),
        html.escape(preview.repo),
        html.escape(preview.description),
        "".join("<span>%s</span>" % (html.escape(str(tag)),) for tag in tags),
    )


def render_page(
    previews: List[Preview], lock: Dict[str, Dict[str, object]], raw_base: str
) -> str:
    cards = [
        _card(preview, "previews/%s.png" % (preview.slug,), lock.get(preview.repo, {}))
        for preview in previews
    ]
    raw_hint = (
        "<p>Every image is also addressable directly, without this page: "
        "<code>%s&lt;owner&gt;__&lt;name&gt;.png</code></p>" % (html.escape(raw_base),)
        if raw_base else ""
    )
    return """<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Security-Policy" content="%s">
    <meta name="referrer" content="no-referrer">
    <meta name="robots" content="index, follow">
    <meta name="description" content="Generated social preview images for %d repositories.">
    <title>Social previews</title>
    <link rel="stylesheet" href="styles.css">
  </head>
  <body>
    <main>
      <h1>Social previews</h1>
      <p class="lede">Generated offline and served from this repository. Each image is a
      deterministic function of its manifest entry, so the same input always produces the
      same file.</p>
      <p class="meta">%d previews &middot; built with gspg %s &middot; no scripts, no web fonts,
      no third-party requests</p>
      <div class="grid">
%s
      </div>
      <footer>
        <p>To use one: download it and upload it under
        <code>Settings &rarr; Social preview</code> on the repository. GitHub offers no
        API for this, so it is the one manual step.</p>
        %s
      </footer>
    </main>
  </body>
</html>
""" % (CSP, len(previews), len(previews), __version__, "\n".join(cards), raw_hint)


def render_index(
    previews: List[Preview], lock: Dict[str, Dict[str, object]], raw_base: str
) -> str:
    """A machine-readable index, for anything that wants the URLs in bulk."""
    payload = {
        "generator": "gspg %s" % (__version__,),
        "count": len(previews),
        "previews": [
            {
                "repo": preview.repo,
                "file": "previews/%s.png" % (preview.slug,),
                "raw_url": (raw_base + preview.slug + ".png") if raw_base else None,
                "pattern": lock.get(preview.repo, {}).get("pattern"),
                "accent": lock.get(preview.repo, {}).get("accent"),
            }
            for preview in previews
        ],
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def build(
    manifest: Manifest,
    lock: Dict[str, Dict[str, object]],
    output_dir: str,
    site_dir: str,
    raw_base: str = "",
) -> Tuple[List[str], List[str]]:
    """Assemble the site into ``site_dir``. Returns (written paths, warnings)."""
    previews = manifest.active()
    png_dir = os.path.join(output_dir, "png")
    site_images = os.path.join(site_dir, "previews")
    os.makedirs(site_images, exist_ok=True)

    warnings: List[str] = []
    included: List[Preview] = []
    for preview in previews:
        source = os.path.join(png_dir, preview.slug + ".png")
        if not os.path.exists(source):
            warnings.append(
                "%s: no rendered PNG, left out of the gallery" % (preview.repo,)
            )
            continue
        shutil.copyfile(source, os.path.join(site_images, preview.slug + ".png"))
        included.append(preview)

    if not included:
        raise RenderError(
            "no rendered previews found in %s. Run `gspg build` first." % (png_dir,)
        )

    # Anything left from a previous build for a repository no longer listed.
    keep = {preview.slug + ".png" for preview in included}
    for name in sorted(os.listdir(site_images)):
        if name.endswith(".png") and name not in keep:
            os.remove(os.path.join(site_images, name))

    written: List[str] = []
    for name, content in (
        ("index.html", render_page(included, lock, raw_base)),
        ("styles.css", STYLESHEET),
        ("index.json", render_index(included, lock, raw_base)),
        # Without this, Pages hides any path beginning with an underscore.
        (".nojekyll", ""),
    ):
        path = os.path.join(site_dir, name)
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(content)
        written.append(path)
    written.append(site_images)
    return written, warnings
